on: push
name: Benchmark
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go-version }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run benchmarks
        run: cd benchmarks && go test && go test -benchmem -bench=.
